### ISSUE TITLE
Parse wast scripts as well

### ISSUE THREAD

**Issue by icefoxen** [pepyakin/wabt-rs#1]
It would be nice to have bindings to parse wast scripts, so we could basically run `wast2json` from a Rust function call.  Unfortunately, wabt does not expose a `wabt_parse_wast()` function as a C function as it does `wabt_parse_wat()`, in https://github.com/WebAssembly/wabt/blob/517f845050f8f462ff2d63de3a85f6b0ce181ada/src/emscripten-helpers.cc .  I'll happily make an upstream PR though.

**Comment by pepyakin** [comment]
Yeah, that will be useful for wasmi as well!
cc https://github.com/pepyakin/wasmi/issues/2

**Comment by icefoxen** [comment]
My PR got merged, so we now have a `wabt_parse_wast()` and other wast-related functions.

Kinda depends on what version of `wabt` you want to bind against, though.  They don't seem to have much of a stable release schedule, so I don't know what the tradeoffs are here.

**Comment by pepyakin** [comment]
im good with picking some master commit (as it is done now)
