### ISSUE TITLE
Supporting new wasm features.

### ISSUE THREAD

**Issue by lachlansneff** [pepyakin/wabt-rs#36]
The wabt implementations (conditionally) supports newer wasm features, like multi-value returns, threads, etc. Can wabt-rs be extended to allow support for those?

**Comment by pepyakin** [comment]
Yeah, I don't see any particular reason why not!

**Comment by pepyakin** [comment]
I think this might be considered as closed after merging https://github.com/pepyakin/wabt-rs/pull/38.

Feel free to reopen if that's not the case!
