### ISSUE TITLE
specify `c++` from environment variable

### ISSUE THREAD

**Issue by nmattia** [pepyakin/wabt-rs#60]
Right now the `wabt-rs` build uses some heuristics to figure out what standard c++ library to include, and whether or not to link it statically:

https://github.com/pepyakin/wabt-rs/blob/2e78683fa27957198804a04540aadad20ba97f1e/wabt-sys/build.rs#L62-L75

I'd love to be able to specify the dependency (and how it's linked) with an environment variable, much like `openssl-sys` does: https://docs.rs/openssl/0.10.25/openssl/#manual

_(quoted)_

A set of environment variables can be used to point openssl-sys towards an OpenSSL installation. They will override the automatic detection logic.

* OPENSSL_DIR - If specified, the directory of an OpenSSL installation. The directory should contain lib and include subdirectories containing the libraries and headers respectively.
* OPENSSL_LIB_DIR and OPENSSL_INCLUDE_DIR - If specified, the directories containing the OpenSSL libraries and headers respectively. This can be used if the OpenSSL installation is split in a nonstandard directory layout.
* OPENSSL_STATIC - If set, the crate will statically link to OpenSSL rather than dynamically link.
* OPENSSL_LIBS - If set, a :-separated list of library names to link to (e.g. ssl:crypto). This can be used if nonstandard library names were used for whatever reason.

**Comment by pepyakin** [comment]
I failed to find openssl's case related, can you elaborate? I am not sure about best-practices for doing that either within the context of `cmake`, if you are aware of any of these please share!

**Comment by nmattia** [comment]
> can you elaborate?

Sure! The `openssl-sys` crate's `build.rs` is configurable through a few environment variables. If `OPENSSL_STATIC` is set, then the config will be `-lstatic=ssl` instead of `-lssl`. In `wabt-rs` it'd be nice to be able to set (e.g.) `WABT_CXX_STATIC` for `-lstatic=c++` (instead of `-lc++`) and potentially `WABT_CXX_LIB=stdc++` if one wants to override the platform's default c++ library.

**Comment by pepyakin** [comment]
I hope that #61 solves this issue for you

**Comment by nmattia** [comment]
This is great, thanks a lot!
