### ISSUE TITLE
Publish new version of the Crate in Crates.io

### ISSUE THREAD

**Issue by syrusakbary** [pepyakin/wabt-rs#65]
We have a PR that adds experimental Wasmer support in Android:
https://github.com/wasmerio/wasmer/pull/1292/files

However, we can't merge it until all dependencies are in Crates.io. Could be possible to publish a new version?

Thanks!

**Comment by pepyakin** [comment]
wabt-sys 0.7.1 is [out](https://crates.io/crates/wabt-sys) (I believe updating only -sys should be enough).
