### ISSUE TITLE
Upgrade upstream wabt

### ISSUE THREAD

**Issue by RReverser** [pepyakin/wabt-rs#67]
It looks like wabt in https://github.com/pepyakin/wabt-rs/tree/master/wabt-sys is quite old now (9 months old), while upstream has gained many new features (e.g. parsing of NAN), changed defaults (e.g. multi-value and sign extension ops are now part of stable), changed some opcodes (e.g. recent SIMD renumbering) and more meanwhile.

Would it be possible to upgrade to the latest release and publish a new version of bindings?

**Comment by pepyakin** [comment]
Hey! wabt-sys 0.7.2 is out.

**Comment by RReverser** [comment]
Thanks!
