### ISSUE TITLE
Reimplement wast scripts to use an external iteration?

### ISSUE THREAD

**Issue by pepyakin** [pepyakin/wabt-rs#8]
#6 implements script parsing as an internal iteration via visitor. 

I wondering, woundn't it be more useful to expose API as an external iterator. 

I.e. 

```rust
let script = parse_script(script_path)?;
loop {
  let cmd = script.next_cmd();
  match cmd {
    Command::DefineModule { .. } => {},
    Command::AssertTrap { .. } => {},
    Command::End => break,
    _ => {},
  }
}
```

This kind of setup have several advantages. It doesn't require us to wrap user errors into our `Error` and woundn't impose on user any particular way of error handling (i.e. user can choose     to `panic` on a failure instead of returning `Error`s). Also, this setup doesn't require user to declare a struct and implement a trait for it, thus might make the code less verbose for the simple use-cases such as testing parsers.

**Comment by NikVolf** [comment]
Absolutely agree
